[package]
name = "rustycity"
version = "0.3.0"
edition = "2024"

[dependencies]
winit = { version = "0.30.12", features = ["serde"] }

wgpu = "27.0.1"
pollster = "0.4.0"
bytemuck = { version = "1.24.0", features = ["derive"] }
glam = "0.30.9"
serde_json = "1.0.145"
toml = "0.9.8"
serde = { version = "1.0.228", features = ["derive"] }
fontdue = "0.9.3"
rect_packer = "0.2.1"
anyhow = "1.0.100"
nanoid = "0.4.0"
notify = "8.2.0"
noise = "0.9.0"
num_cpus = "1.17.0"
crossbeam-channel = "0.5.15"
fastnoise-lite = "1.1.1"
rand = "0.8.5"
rayon = "1.11.0"