[package]
name = "Rusty_Skylines"
version = "0.4.0"
edition = "2024"

[dependencies]
winit = { version = "0.30.12", features = ["serde"] }

wgpu = "28.0.0"
pollster = "0.4.0"
bytemuck = { version = "1.24.0", features = ["derive"] }
glam = "0.30.9"
toml = "0.9.8"
serde = { version = "1.0.228", features = ["derive"] }
fontdue = "0.9.3"
rect_packer = "0.2.1"
anyhow = "1.0.100"
notify = "8.2.0"
num_cpus = "1.17.0"
crossbeam-channel = "0.5.15"
fastnoise-lite = "1.1.1"
rand = "0.9.2"
zstd = "0.13.3"
postcard = { version = "1.1.3", features = ["use-std"] }
serde_yaml = "0.9.34+deprecated"

[profile.fastdev]
inherits = "release"      # start with release defaults
opt-level = 1         # override with release-level speed
debug = true           # keep debug symbols
split-debuginfo = "packed"
overflow-checks = true
lto = false
